namespace Shenoy.Quiz.Model
{
    // If I were a C# enum ...
    public enum Person
    {
        Adarsh,
        AjayBhat,
        AmitB,
        Anirudh,
        Antariksh,
        Aswath,
        Avinash,
        BooBoo,
        Gayathri,
        Hannibal,
        Harish,
        MaiDang,
        Maitrey,
        Mythreyi,
        Michael,
        Mihir,
        Nandini,
        Pallavi,
        Parth,
        Prabirendra,
        Pranav,
        Priyananda,
        RohitSud,
        Samarth,
        Shashank,
        SriramS,
        Suchitra,
        SudhirAP,
        SuhasRao,
        Surinderjeet,
        Vashutosh,
        Yogesh
    }
}
